### ISSUE TITLE
needs a README with installation instructions

### ISSUE THREAD

**Issue by jidicula** [Adoria/Martlet#2]

**Comment by Adoria** [comment]
Added. Let me know if it's missing anything.

**Comment by jidicula** [comment]
Can you include what the exact commands are for installing the pip dependencies?

**Comment by Adoria** [comment]
I didn't include them on purpose because the links to the dependencies already contain that information. However, it does feel off that I made no attempts to redirect people there... I updated README to better reflect installation instructions for now, but let me know if you feel adding the actual commands is a better choice in the long run.

Thanks!
